// Shuffled once on 2026-09-14 (seed 20260914). Never shuffle at runtime.
// One prompt per Israel game day, shared by its 03:00 and 15:00 rounds.
// Keep this order stable; old rounds and their answers must retain their prompt.
export const CATEGORY_SCHEDULE_START = '2026-09-14';
export const CATEGORY_SCHEDULE = [
  {"id":70,"prompt":"Name something you wouldn’t lend a stranger."},
  {"id":57,"prompt":"Name a quality of a good friend."},
  {"id":29,"prompt":"Name something you find on a beach."},
  {"id":35,"prompt":"Name somewhere people go on vacation."},
  {"id":55,"prompt":"Name something people lie about."},
  {"id":50,"prompt":"Name something you forget to charge."},
  {"id":49,"prompt":"Name something you take when leaving home."},
  {"id":38,"prompt":"Name somewhere you go on a date."},
  {"id":74,"prompt":"Name a fairy-tale character."},
  {"id":51,"prompt":"Name something people fear."},
  {"id":40,"prompt":"Name somewhere you wouldn’t want to get stuck."},
  {"id":100,"prompt":"Name something worth waiting for."},
  {"id":68,"prompt":"Name something you take to the beach."},
  {"id":42,"prompt":"Name a kitchen appliance."},
  {"id":23,"prompt":"Name a wild animal."},
  {"id":75,"prompt":"Name a board game."},
  {"id":16,"prompt":"Name a spice."},
  {"id":64,"prompt":"Name an accessory."},
  {"id":2,"prompt":"Name an animal."},
  {"id":30,"prompt":"Name something you see in the sky."},
  {"id":25,"prompt":"Name a bird."},
  {"id":63,"prompt":"Name a type of shoe."},
  {"id":98,"prompt":"Name something you shouldn’t touch."},
  {"id":32,"prompt":"Name an island."},
  {"id":59,"prompt":"Name something that ruins a date."},
  {"id":84,"prompt":"Name something round."},
  {"id":61,"prompt":"Name something you wear in winter."},
  {"id":28,"prompt":"Name a tree."},
  {"id":81,"prompt":"Name something red."},
  {"id":31,"prompt":"Name a city."},
  {"id":10,"prompt":"Name a musical instrument."},
  {"id":71,"prompt":"Name a superhero."},
  {"id":9,"prompt":"Name a job."},
  {"id":95,"prompt":"Name something you’d save from a fire."},
  {"id":72,"prompt":"Name a cartoon character."},
  {"id":44,"prompt":"Name something in a bedroom."},
  {"id":87,"prompt":"Name something sticky."},
  {"id":86,"prompt":"Name something loud."},
  {"id":14,"prompt":"Name a dessert."},
  {"id":18,"prompt":"Name a cheese."},
  {"id":21,"prompt":"Name a pet."},
  {"id":96,"prompt":"Name something you’d want on a deserted island."},
  {"id":54,"prompt":"Name something people argue about."},
  {"id":34,"prompt":"Name a planet."},
  {"id":12,"prompt":"Name an ice cream flavor."},
  {"id":85,"prompt":"Name something soft."},
  {"id":92,"prompt":"Name something you do before bed."},
  {"id":65,"prompt":"Name something you wear on your head."},
  {"id":67,"prompt":"Name something you pack for a trip."},
  {"id":7,"prompt":"Name a drink."},
  {"id":62,"prompt":"Name something you wear in summer."},
  {"id":15,"prompt":"Name a snack."},
  {"id":22,"prompt":"Name a farm animal."},
  {"id":80,"prompt":"Name something you do at a party."},
  {"id":69,"prompt":"Name something you take camping."},
  {"id":26,"prompt":"Name an insect."},
  {"id":78,"prompt":"Name a music genre."},
  {"id":73,"prompt":"Name a movie villain."},
  {"id":83,"prompt":"Name something green."},
  {"id":4,"prompt":"Name a fruit."},
  {"id":79,"prompt":"Name a hobby."},
  {"id":76,"prompt":"Name a video game."},
  {"id":5,"prompt":"Name a vegetable."},
  {"id":82,"prompt":"Name something yellow."},
  {"id":99,"prompt":"Name something that feels like home."},
  {"id":93,"prompt":"Name something you do when you’re bored."},
  {"id":48,"prompt":"Name something you always lose."},
  {"id":33,"prompt":"Name a continent."},
  {"id":94,"prompt":"Name something you do when you can’t sleep."},
  {"id":47,"prompt":"Name something you clean every day."},
  {"id":36,"prompt":"Name somewhere you have to be quiet."},
  {"id":6,"prompt":"Name a sport."},
  {"id":60,"prompt":"Name something that helps you relax."},
  {"id":91,"prompt":"Name something you do first thing in the morning."},
  {"id":53,"prompt":"Name something that makes people cry."},
  {"id":11,"prompt":"Name a pizza topping."},
  {"id":45,"prompt":"Name something you keep in a drawer."},
  {"id":27,"prompt":"Name a flower."},
  {"id":17,"prompt":"Name a sauce."},
  {"id":39,"prompt":"Name somewhere children love going."},
  {"id":58,"prompt":"Name something that makes someone attractive."},
  {"id":37,"prompt":"Name somewhere you wait in line."},
  {"id":43,"prompt":"Name something in a bathroom."},
  {"id":3,"prompt":"Name a country."},
  {"id":66,"prompt":"Name something you keep in your pocket."},
  {"id":89,"prompt":"Name something fragile."},
  {"id":77,"prompt":"Name a toy."},
  {"id":90,"prompt":"Name something that smells good."},
  {"id":20,"prompt":"Name something you put in a sandwich."},
  {"id":13,"prompt":"Name a breakfast food."},
  {"id":52,"prompt":"Name something that makes people smile."},
  {"id":97,"prompt":"Name something you’d buy if you became rich."},
  {"id":1,"prompt":"Name a color."},
  {"id":56,"prompt":"Name something people wish they had more of."},
  {"id":19,"prompt":"Name a nut."},
  {"id":88,"prompt":"Name something expensive."},
  {"id":8,"prompt":"Name a feeling."},
  {"id":24,"prompt":"Name a sea creature."},
  {"id":46,"prompt":"Name something you hang on a wall."},
  {"id":41,"prompt":"Name a piece of furniture."},
] as const;

export function categoryForRound(roundId: string) {
  const date = roundId.slice(0, 10);
  const dayOffset = Math.floor((Date.parse(date + 'T00:00:00Z') - Date.parse(CATEGORY_SCHEDULE_START + 'T00:00:00Z')) / 86_400_000);
  const day = Number.isFinite(dayOffset) ? Math.max(0, dayOffset) : 0;
  // Repeat the saved sequence after day 100 until a new season is defined.
  return { ...CATEGORY_SCHEDULE[day % CATEGORY_SCHEDULE.length], day: day + 1 };
}

