create table public.wurd_replies (
  id bigint generated by default as identity primary key,
  daily_word_id bigint not null references public.daily_words(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  word text not null,
  created_at timestamptz not null default now(),
  constraint wurd_replies_one_per_user unique (daily_word_id, user_id),
  constraint wurd_replies_word_length check (char_length(word) between 1 and 20),
  constraint wurd_replies_one_word check (word !~ '[[:space:]]' and word = btrim(word))
);

create index wurd_replies_daily_word_created_idx
  on public.wurd_replies (daily_word_id, created_at);
create index wurd_replies_user_idx on public.wurd_replies (user_id);

alter table public.wurd_replies enable row level security;

create policy "Authenticated users can read replies to active Wurds"
on public.wurd_replies
for select
to authenticated
using (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.daily_words word
    where word.id = wurd_replies.daily_word_id
      and word.replaced_at is null
      and word.created_at > now() - interval '24 hours'
      and word.created_at <= now()
  )
);

grant select on public.wurd_replies to authenticated;
revoke insert, update, delete on public.wurd_replies from anon, authenticated;

create function public.reply_to_wurd(
  p_daily_word_id bigint,
  p_word text
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  clean_word text := upper(btrim(p_word));
  reply_id bigint;
begin
  if actor is null then
    raise exception 'Authentication required';
  end if;
  if clean_word is null
    or char_length(clean_word) not between 1 and 20
    or clean_word ~ '[[:space:]]'
  then
    raise exception 'A reply must be one Wurd of up to 20 characters';
  end if;
  perform 1
    from public.daily_words word
    where word.id = p_daily_word_id
      and word.user_id <> actor
      and word.replaced_at is null
      and word.created_at > now() - interval '24 hours'
      and word.created_at <= now()
    for update;
  if not found then
    raise exception 'This Wurd is not available to reply to';
  end if;
  if exists (
    select 1 from public.wurd_replies reply
    where reply.daily_word_id = p_daily_word_id
      and reply.user_id = actor
  ) then
    raise exception 'You already replied to this Wurd';
  end if;

  insert into public.wurd_replies (daily_word_id, user_id, word)
  values (p_daily_word_id, actor, upper(clean_word))
  returning id into reply_id;

  return reply_id;
end;
$$;

revoke all on function public.reply_to_wurd(bigint, text) from public, anon;
grant execute on function public.reply_to_wurd(bigint, text) to authenticated;

create function public.wurd_reply_thread(p_daily_word_id bigint)
returns table (
  id bigint,
  daily_word_id bigint,
  user_id uuid,
  username text,
  avatar_url text,
  word text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    reply.id,
    reply.daily_word_id,
    reply.user_id,
    profile.username,
    case
      when profile.level >= 5
        and profile.avatar_url = profile.id::text || '/avatar.webp'
      then profile.avatar_url
      else null
    end,
    reply.word,
    reply.created_at
  from public.wurd_replies reply
  join public.profiles profile on profile.id = reply.user_id
  join public.daily_words daily on daily.id = reply.daily_word_id
  where (select auth.uid()) is not null
    and daily.id = p_daily_word_id
    and daily.replaced_at is null
    and daily.created_at > now() - interval '24 hours'
    and daily.created_at <= now()
  order by reply.created_at, reply.id;
$$;

revoke all on function public.wurd_reply_thread(bigint) from public, anon;
grant execute on function public.wurd_reply_thread(bigint) to authenticated;

drop function if exists public.feed_words(date, integer, boolean);

create function public.feed_words(
  p_date date,
  p_limit integer default 8,
  p_friends_only boolean default false
) returns table (
  id bigint,
  user_id uuid,
  username text,
  display_name text,
  avatar_url text,
  city text,
  country_code text,
  word text,
  emoji text,
  color text,
  word_style text,
  animation text,
  local_date date,
  created_at timestamptz,
  echo_count bigint,
  reply_count bigint,
  replies jsonb,
  spoke_count bigint,
  echoed_by_me boolean,
  my_echo_strength smallint
)
language sql
stable
security definer
set search_path = ''
as $$
  with active_words as (
    select distinct on (candidate.user_id)
      candidate.*
    from public.daily_words candidate
    where candidate.replaced_at is null
      and candidate.created_at > now() - interval '24 hours'
      and candidate.created_at <= now()
    order by candidate.user_id, candidate.created_at desc, candidate.id desc
  )
  select
    daily.id,
    daily.user_id,
    profile.username,
    profile.display_name,
    case
      when profile.level >= 5
        and profile.avatar_url = profile.id::text || '/avatar.webp'
      then profile.avatar_url
      else null
    end,
    daily.city,
    daily.country_code,
    daily.word,
    daily.emoji,
    daily.color,
    daily.word_style,
    daily.animation,
    daily.local_date,
    daily.created_at,
    echo_stats.echo_count,
    reply_stats.reply_count,
    reply_stats.replies,
    (
      select count(distinct recent.user_id)
      from active_words recent
      where not p_friends_only
        or recent.user_id = (select auth.uid())
        or exists (
          select 1 from public.friendships recent_friendship
          where recent_friendship.status = 'accepted'
            and (
              (recent_friendship.requester_id = (select auth.uid()) and recent_friendship.addressee_id = recent.user_id)
              or (recent_friendship.addressee_id = (select auth.uid()) and recent_friendship.requester_id = recent.user_id)
            )
        )
    ),
    echo_stats.my_echo_strength > 0,
    echo_stats.my_echo_strength
  from active_words daily
  join public.profiles profile on profile.id = daily.user_id
  cross join lateral (
    select
      coalesce(sum(echo.strength), 0)::bigint as echo_count,
      coalesce(max(echo.strength) filter (where echo.user_id = (select auth.uid())), 0)::smallint as my_echo_strength
    from public.echoes echo
    where echo.daily_word_id = daily.id
  ) echo_stats
  cross join lateral (
    select count(*)::bigint as reply_count,
      coalesce(jsonb_agg(jsonb_build_object(
        'id', reply.id, 'daily_word_id', reply.daily_word_id,
        'user_id', reply.user_id, 'username', replier.username,
        'avatar_url', null, 'word', reply.word, 'created_at', reply.created_at
      ) order by reply.created_at, reply.id), '[]'::jsonb) as replies
    from public.wurd_replies reply
    join public.profiles replier on replier.id = reply.user_id
    where reply.daily_word_id = daily.id
  ) reply_stats
  where (select auth.uid()) is not null
    and (
      not p_friends_only
      or daily.user_id = (select auth.uid())
      or exists (
        select 1 from public.friendships friendship
        where friendship.status = 'accepted'
          and (
            (friendship.requester_id = (select auth.uid()) and friendship.addressee_id = daily.user_id)
            or (friendship.addressee_id = (select auth.uid()) and friendship.requester_id = daily.user_id)
          )
      )
    )
  order by (echo_stats.echo_count * 2 + reply_stats.reply_count) desc, daily.created_at desc
  limit nullif(greatest(p_limit, 0), 0);
$$;

revoke all on function public.feed_words(date, integer, boolean) from public, anon;
grant execute on function public.feed_words(date, integer, boolean) to authenticated;
